x-logging:
  &default-logging
  driver: fluentd
  options:
    fluentd-async-connect: "true"
    tag: "docker.{{.Name}}"

x-single-replicated:
  &single-replicated
  mode: replicated
  replicas: 1

x-multi-replicated:
  &multi-replicated
  mode: replicated
  replicas: ${SWARM_REPLICAS:-3}
  placement:
    max_replicas_per_node: 1

services:
  fluentd:
    hostname: "fl-{{.Node.Hostname}}"
    logging: *default-logging
    deploy: *single-replicated
  redis:
    hostname: "re-{{.Node.Hostname}}"
    logging: *default-logging
    deploy: *single-replicated
  rabbitmq:
    hostname: "mq-{{.Node.Hostname}}"
    logging: *default-logging
    configs:
      - source: rabbitmq-config-cluster
        target: /etc/rabbitmq/conf.d/50-cluster.conf
    environment:
      RABBITMQ_ERLANG_COOKIE: SECRET_COOKIE
    deploy: *multi-replicated
  jobmngrd:
    hostname: "jm-{{.Node.Hostname}}"
    logging: *default-logging
    deploy: *multi-replicated
  kengine:
    hostname: "ke-{{.Node.Hostname}}"
    logging: *default-logging
    deploy: *multi-replicated
  kompira:
    hostname: "ap-{{.Node.Hostname}}"
    logging: *default-logging
    deploy: *multi-replicated
  nginx:
    hostname: "nx-{{.Node.Hostname}}"
    logging: *default-logging
    deploy: *multi-replicated

configs:
  rabbitmq-config-cluster:
    file: ./rabbitmq-cluster.conf
