services:
  fluentd:
    container_name: kompira-logger
    build:
      context: .
      dockerfile: ../Dockerfiles/Dockerfile.fluentd
    volumes:
      - ../configs/fluentd.conf:/fluentd/etc/fluent.conf:ro
      - ./log:/var/log/fluentd
    user: "${LOCAL_UID}:${LOCAL_GID}"
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    restart: always
  kompira:
    container_name: kompira-app
    image: kompira.azurecr.io/kompira-enterprise:latest
    environment:
      - DATABASE_URL=pgsql://kompira:kompira@host.docker.internal:5432/kompira
      - AMQP_URL=amqp://guest:guest@rabbitmq:5672
      - CACHE_URL=redis://redis:6379
      - TZ=Asia/Tokyo
    volumes:
      - kompira_var:/var/opt/kompira
      - ../configs/kompira_audit.yaml:/opt/kompira/kompira_audit.yaml:ro
    command: ["uwsgi"]
    stop_signal: SIGINT
    extra_hosts:
      - host.docker.internal:host-gateway
    logging:
      driver: fluentd
      options:
        fluentd-async-connect: "true"
        tag: "docker.{{.Name}}"
    depends_on:
      - fluentd
      - kengine
    restart: always
  kengine:
    container_name: kompira-engine
    image: kompira.azurecr.io/kompira-enterprise:latest
    environment:
      - DATABASE_URL=pgsql://kompira:kompira@host.docker.internal:5432/kompira
      - AMQP_URL=amqp://guest:guest@rabbitmq:5672
      - CACHE_URL=redis://redis:6379
      - TZ=Asia/Tokyo
    volumes:
      - kompira_var:/var/opt/kompira
      - ../configs/kompira_audit.yaml:/opt/kompira/kompira_audit.yaml:ro
    command: ["kompirad"]
    ulimits:
      nproc: 65535
      nofile: 65535
    extra_hosts:
      - host.docker.internal:host-gateway
    logging:
      driver: fluentd
      options:
        fluentd-async-connect: "true"
        tag: "docker.{{.Name}}"
    depends_on:
      - fluentd
      - rabbitmq
    restart: always
  jobmngrd:
    container_name: kompira-jobmngr
    image: kompira.azurecr.io/kompira-enterprise:latest
    volumes:
      - kompira_var:/var/opt/kompira
      - ../configs/kompira.conf:/opt/kompira/kompira.conf:ro
    command: ["jobmngrd"]
    ulimits:
      nproc: 65535
      nofile: 65535
    logging:
      driver: fluentd
      options:
        fluentd-async-connect: "true"
        tag: "docker.{{.Name}}"
    depends_on:
      - fluentd
      - rabbitmq
    restart: always
  redis:
    container_name: kompira-cache
    image: redis:7.2-alpine
    volumes:
      - kompira_redis:/data
    logging:
      driver: fluentd
      options:
        fluentd-async-connect: "true"
        tag: "docker.{{.Name}}"
    depends_on:
      - fluentd
    restart: always
  nginx:
    container_name: kompira-web
    image: nginx:1.25-alpine
    volumes:
      - kompira_var:/var/opt/kompira
      - ../configs/nginx-default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
    logging:
      driver: fluentd
      options:
        fluentd-async-connect: "true"
        tag: "docker.{{.Name}}"
    depends_on:
      - fluentd
      - kompira
    restart: always
  rabbitmq:
    container_name: kompira-mq
    hostname: rabbitmq-server
    image: rabbitmq:3.12-alpine
    volumes:
      - kompira_mq:/var/lib/rabbitmq     # volume名を明示的に指定 (指定しないとハッシュ化された文字列のボリューム名が使われてゴミが増える)
    environment:
      RABBITMQ_DATA_DIR: /var/lib/rabbitmq    # デフォルト値なので指定不要だが、ボリュームのマウントポイントと一致させるために明示的に指定しておく
    logging:
      driver: fluentd
      options:
        fluentd-async-connect: "true"
        tag: "docker.{{.Name}}"
    depends_on:
      - fluentd
    restart: always

volumes:
  kompira_var:
  kompira_mq:
  kompira_redis:
