services:
  jobmngrd:
    image: ${KOMPIRA_IMAGE_NAME:-kompira.azurecr.io/kompira-enterprise}:${KOMPIRA_IMAGE_TAG:-latest}
    hostname: jm.${HOSTNAME}
    environment:
      - TZ=${TZ:-Asia/Tokyo}
    configs:
      - source: kompira-config
        target: /opt/kompira/kompira.conf
    volumes:
      - ${KOMPIRA_VAR_DIR:-kompira_var}:/var/opt/kompira
    command: ["jobmngrd"]
    ulimits:
      nproc: 65535
      nofile: 65535
configs:
  kompira-config:
    file: ../../configs/kompira.conf
volumes:
  kompira_var:
