services:
  nginx:
    image: registry.hub.docker.com/library/nginx:1.25-alpine
    hostname: nginx
    environment:
      - TZ=${TZ:-Asia/Tokyo}
    configs:
      - source: nginx-config-default
        target: /etc/nginx/conf.d/default.conf
      - source: nginx-config-ssl
        target: /etc/nginx/conf.d/ssl.conf
    volumes:
      - ${KOMPIRA_VAR_DIR:-kompira_var}:/var/opt/kompira
      - ${KOMPIRA_SSL_DIR:-../../ssl}:/etc/nginx/ssl
    ports:
      - "80:80"
      - "443:443"
configs:
  nginx-config-default:
    file: ../../configs/nginx-default.conf
  nginx-config-ssl:
    file: ../../configs/nginx-ssl.conf
volumes:
  kompira_var:
