services:
  nginx:
    image: registry.hub.docker.com/library/nginx:1.25-alpine
    hostname: nx-${HOSTNAME}
    environment:
      - TZ=${TZ:-Asia/Tokyo}
    configs:
      - source: nginx-config
        target: /etc/nginx/conf.d/default.conf
    volumes:
      - ${KOMPIRA_VAR_DIR:-kompira_var}:/var/opt/kompira
      - ${KOMPIRA_SSL_DIR:-../../ssl}:/etc/nginx/ssl:ro
    ports:
      - "80:80"
      - "443:443"
configs:
  nginx-config:
    file: ../../configs/nginx-ssl.conf
volumes:
  kompira_var:
