x-logging:
  &default-logging
  driver: local
  # options:
  #   tag: "docker.{{.Name}}"

services:
  redis:
    logging: *default-logging
    restart: always
  rabbitmq:
    logging: *default-logging
    restart: always
  jobmngrd:
    logging: *default-logging
    depends_on:
      - rabbitmq
    restart: always
  kengine:
    volumes:
      - type: bind
        source: ./.secret_key
        target: /var/opt/kompira/.secret_key
    logging: *default-logging
    depends_on:
      - redis
      - rabbitmq
    restart: always
  kompira:
    volumes:
      - type: bind
        source: ./.secret_key
        target: /var/opt/kompira/.secret_key
    logging: *default-logging
    depends_on:
      - redis
      - kengine
    restart: always
  nginx:
    logging: *default-logging
    depends_on:
      - kompira
    restart: always
