x-deploy:
  &default-deploy
  resources:
    limits:
      cpus: ${RESOURCES_LIMITS_CPUS:-0.50}

services:
  redis:
    restart: always
    deploy: *default-deploy
  rabbitmq:
    restart: always
    deploy: *default-deploy
  jobmngrd:
    command: ["docker-entrypoint.sh", "jobmngrd"]
    depends_on:
      - rabbitmq
    restart: always
    deploy: *default-deploy
  kengine:
    command: ["docker-entrypoint.sh", "kompirad"]
    depends_on:
      - rabbitmq
    restart: always
    deploy: *default-deploy
  kompira:
    command: ["docker-entrypoint.sh", "uwsgi"]
    depends_on:
      - kengine
    restart: always
    deploy: *default-deploy
  nginx:
    volumes:
      - kompira_nginx_conf:/etc/nginx/conf.d
    depends_on:
      - kompira
    restart: always
    deploy: *default-deploy

volumes:
  kompira_ssl:
    driver: azure_file
    driver_opts:
      share_name: kompira-ssl
      storage_account_name: ${STORAGE_ACCOUNT_NAME:?STORAGE_ACCOUNT_NAME must be set}
  kompira_var:
    driver: azure_file
    driver_opts:
      share_name: kompira-var
      storage_account_name: ${STORAGE_ACCOUNT_NAME:?STORAGE_ACCOUNT_NAME must be set}
  kompira_nginx_conf:
    driver: azure_file
    driver_opts:
      share_name: kompira-nginx-conf
      storage_account_name: ${STORAGE_ACCOUNT_NAME:?STORAGE_ACCOUNT_NAME must be set}
