x-logging:
  &default-logging
  driver: fluentd
  options:
    fluentd-async-connect: "true"
    tag: "docker.{{.Name}}"

services:
  fluentd:
    logging: *default-logging
    restart: always
  redis:
    logging: *default-logging
    depends_on:
      - fluentd
    restart: always
  postgres:
    logging: *default-logging
    depends_on:
      - fluentd
    restart: always
  rabbitmq:
    logging: *default-logging
    depends_on:
      - fluentd
    restart: always
  jobmngrd:
    logging: *default-logging
    depends_on:
      - fluentd
      - rabbitmq
    restart: always
  kengine:
    logging: *default-logging
    depends_on:
      - fluentd
      - redis
      - postgres
      - rabbitmq
    restart: always
  kompira:
    logging: *default-logging
    depends_on:
      - fluentd
      - redis
      - postgres
      - kengine
    restart: always
  nginx:
    logging: *default-logging
    depends_on:
      - fluentd
      - kompira
    restart: always
